name: authentication_qpp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'  # SDK sürüm aralığını mevcut sürümünüze uygun hale getirdik

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # lint sürümünü düşürdük

flutter:
  uses-material-design: true